filebeat.registry.path: registry.elasticsearch

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data/current/*-*.log

filebeat.config.modules:
  path: /etc/filebeat/modules.d/*.yml
  reload.enabled: false

setup.template:
  enabled: false
  settings:
    index.number_of_shards: 1

setup.kibana:
  host: "kibana.elk.svc.cluster.local:5601"

output.elasticsearch:
  protocol: https
  ssl.verification_mode: none
  hosts: ["elasticsearch-master.elk.svc.cluster.local:9200"]
  username: 'elastic'
  password: 'xxxxx'
  pipeline: test_current_index
  index: "test_current-%{[dissect.yyyymm]}"

processors:
  - decode_csv_fields:
      fields:
        message: decoded.csv
      separator: ","
      ignore_missing: false
      overwrite_keys: true
      trim_leading_space: false
      fail_on_error: true

  - dissect:
      field: log.file.path
      tokenizer: "/data/%{account}/%{account}-%{yyyymm}.log"

logging.level: debug
monitoring.enabled: false

setup.ilm.enabled: false

