apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bastion-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: bastion-pvc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bastion-pvc
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://ap-northeast-2a/vol-051ffb6ca2e07247c
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  volumeMode: Filesystem
