apiVersion: v1
kind: Pod
metadata:
  name: bastion
spec:
  containers:
  - name: bastion
    image: ubuntu:18.04
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: bastion-pvc
  nodeSelector:
    team: devops
    environment: dev

---

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: bastion
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: bastion
#  template:
#    metadata:
#      labels:
#        app: bastion
#    spec:
#      containers:
#        - name: bastion
#          image: ubuntu:18.04
#          command: [ "/bin/sh" ]
#          args: [ "-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done" ]
#          resources:
#            requests:
#              memory: "128Mi"
#              cpu: "500m"
#          volumeMounts:
#            - name: persistent-storage
#              mountPath: /data
#      volumes:
#        - name: persistent-storage
#          persistentVolumeClaim:
#            claimName: bastion-pvc
#      nodeSelector:
#        team: devops
#        environment: dev

