apiVersion: v1
kind: Pod
metadata:
  name: test-app2
spec:
  containers:
  - name: test-app2
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "sleep 10000"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim-test3
