apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ns-list
subjects:
- kind: User
  name: doogee.hong
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: ns-list
  apiGroup: rbac.authorization.k8s.io
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: devops
  name: devops-manager-binding
subjects:
- kind: User
  name: doogee.hong
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devops-manager
  apiGroup: rbac.authorization.k8s.io
