kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ns-list
rules:
- apiGroups: [""]
  resources: ["namespaces", "customresourcedefinitions"]
  verbs: ["get", "list", "watch"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: devops
  name: devops-manager
rules:
- apiGroups: ["", "metrics.k8s.io", "extensions", "apps", "batch"]
  resources: ["*"]
  verbs: ["*"]
