apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Terraform
    terraform.io/module: terraform-aws-modules.eks.aws
data:
  mapAccounts: |
    - "aws_account_id"
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::aws_account_id:role/ec2_role"
      "username": "system:node:{{EC2PrivateDNSName}}"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::aws_account_id:role/eks_role"
      "username": "eks_role"
  mapUsers: |
    - "groups":
      - "system:masters"
      "userarn": "arn:aws:iam::aws_account_id:user/devops"
      "username": "devops"
    - "groups":
      - "system:masters"
      "userarn": "arn:aws:iam::aws_account_id:user/doohee.hong"
      "username": "doohee.hong"
