filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/pods/**/*.log
        - /root/tmp/*.log

    setup.template.settings:
      index.number_of_shards: 1

    setup.template:
      name: 'api-access'
      pattern: 'api-access-*'
      enabled: false

    output.logstash:
      index: "api-access-%{+yyyy.MM.dd}"
      protocol: http
	  hosts: ["logstash-logstash.elk.svc.cluster.local:5044"]
      processors:
        - decode_json_fields:
          fields: ["log"]
          target: ""
          overwrite_keys: true

#    output.elasticsearch:
#      index: "api-access-%{+yyyy.MM.dd}"
#      protocol: http
#      host: '${NODE_NAME}'
#      hosts: ["http://es.elk.eks_project.eks_domain:80"]
#      username: 'elastic'
#      password: 'ADMIN_PASSWORD'
#      processors:
#        - decode_json_fields:
#          fields: ["log"]
#          target: ""
#          overwrite_keys: true

#      - add_kubernetes_metadata:
#          host: ${NODE_NAME}
#          default_indexers.enabled: false
#          default_matchers.enabled: false
#          matchers:
#            - logs_path:
#                logs_path: '/var/lib/pods/*.*'
#                resource_type: 'pod'

extraEnvs:
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password

secretMounts:
  - name: elastic-certificates
    secretName: elastic-certificates
    path: /usr/share/filebeat/config/certs

nodeSelector:
  team: "TEAM"
  environment: "STAGING"

podSecurityContext:
  runAsUser: 0
  privileged: false

readinessProbe:
  exec:
    command:
      - sh
      - -c
      - |
        #!/usr/bin/env bash -e
        ls
#        filebeat test output
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
