kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elk-bastion-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: elk-bastion
spec:
  containers:
  - name: elk-bastion
    image: ubuntu:18.04
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: elk-bastion-pvc
  nodeSelector:
    team: devops
    environment: elk
