serviceAccount:
  annotations:
#    eks.amazonaws.com/role-arn: arn:aws:iam::aws_account_id:role/cluster_iam_role
    eks.amazonaws.com/role-arn: cert_manager_irsa_role_arn

#installCRDs: true

securityContext:
  enabled: true
  fsGroup: 1001

extraArgs:
  - --issuer-ambient-credentials=true
  - --cluster-issuer-ambient-credentials=true
