apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    kubernetes.io/psp: eks.privileged
    deployment.kubernetes.io/revision: "3"
    meta.helm.sh/release-name: cluster-autoscaler
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/instance: cluster-autoscaler
  name: cluster-autoscaler-aws-cluster-autoscaler-chart
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: cluster-autoscaler
      app.kubernetes.io/name: aws-cluster-autoscaler-chart
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: cluster-autoscaler
        app.kubernetes.io/name: aws-cluster-autoscaler-chart
    spec:
      containers:
      - command:
        - ./cluster-autoscaler
        - --v=4
        - --stderrthreshold=info
        - --cloud-provider=aws
        - --skip-nodes-with-local-storage=false
        - --expander=least-waste
        - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/eks_project
        - --balance-similar-node-groups
        - --skip-nodes-with-system-pods=false
        - --namespace=kube-system
        - --logtostderr=true
        env:
        - name: AWS_REGION
          value: aws_region
        image: us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v1.18.3
        imagePullPolicy: IfNotPresent
        name: aws-cluster-autoscaler-chart
      serviceAccount: cluster-autoscaler-aws-cluster-autoscaler-chart
      serviceAccountName: cluster-autoscaler-aws-cluster-autoscaler-chart
